# Provision GCP GKE cluster
apiVersion: xl-deploy/v1
kind: Infrastructure
spec:
- name: scott-gcp-final
  type: core.Directory
  children:
  - name: gcp-terraform
    type: overthere.LocalHost
    os: UNIX
    children:
    - name: terraform-client
      type: terraform.TerraformClient
      path: '/usr/local/bin' # for local installation
      workingDirectory: '/tmp/scott-gcp-final' # for local installation

---
apiVersion: xl-deploy/v1
kind: Environments
spec:
- name: scott-gcp-final
  type: core.Directory
  children:
  - name: gcp-terraform
    type: udm.Environment
    members:
    - Infrastructure/scott-gcp-final/gcp-terraform
    - Infrastructure/scott-gcp-final/gcp-terraform/terraform-client