apiVersion: xl-release/v1
kind: Templates
spec:
- name: scott-micro-final
  type: xlrelease.Folder
  children:
  - name: scott-micro-final-destroy
    type: xlrelease.Release
    description: |
      This XL Release template shows how to undeploy an application, based on microservices architecture, to AWS EKS using XL Deploy.
    tags:
    - AWS
    - EKS
    - scott-micro-final
    scriptUsername: !value XL_RELEASE_USERNAME
    scriptUserPassword: !value XL_RELEASE_PASSWORD
    phases:
    - name: Undeploy Application
      type: xlrelease.Phase
      tasks:
      - name: Undeploy stateless services
        type: xlrelease.ParallelGroup
        tasks:
        - name: Undeploy registry svc
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/scott-micro-final/aws-eks-scott-micro-final/scott-micro-final-registry
        - name: Undeploy invoice svc
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/scott-micro-final/aws-eks-scott-micro-final/scott-micro-final-invoice
        - name: Undeploy notification svc
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/scott-micro-final/aws-eks-scott-micro-final/scott-micro-final-notification
        - name: Undeploy store svc
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/scott-micro-final/aws-eks-scott-micro-final/scott-micro-final-store
      - name: Undeploy stateful services
        type: xlrelease.ParallelGroup
        tasks:
        - name: Undeploy invoice mysql svc
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/scott-micro-final/aws-eks-scott-micro-final/scott-micro-final-invoice-mysql
        - name: Undeploy store mysql svc
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/scott-micro-final/aws-eks-scott-micro-final/scott-micro-final-store-mysql
        - name: Undeploy notification mongodb svc
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/scott-micro-final/aws-eks-scott-micro-final/scott-micro-final-notification-mongodb
      
      # Un-provision namespace
      - name: Undeploy xl-demo namespace
        type: xldeploy.Undeploy
        server: XL Deploy
        deployedApplication: Environments/scott-micro-final/aws-eks-scott-micro-final/scott-micro-final-namespace
      
    
    # De-provision Infra
    - name: Deprovision Infrastructure
      color: '#ff9e3b'
      type: xlrelease.Phase
      tasks:
      - name: Deprovision AWS EKS cluster
        type: xlrelease.SequentialGroup
        tasks:
        - name: Deprovision EKS config map for workers
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/scott-micro-final/aws-eks-scott-micro-final-kube-system/scott-micro-final-k8s-configmap
        - name: Deprovision EKS workers nodes
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/scott-micro-final/aws-cloudformation-scott-micro-final/scott-micro-final-cloudformation-eks-workers
        - name: Deprovision EKS master node
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/scott-micro-final/aws-cloudformation-scott-micro-final/scott-micro-final-cloudformation-eks-master
      - name: Delete artifacts from S3
        type: xlrelease.SequentialGroup
        tasks:
        - name: Delete artifacts from S3
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/scott-micro-final/aws-cloudformation-scott-micro-final/scott-micro-final-lambda-artifacts
        - name: Delete S3 bucket
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/scott-micro-final/aws-cloudformation-scott-micro-final/scott-micro-final-lambda-bucket
      - name: Deprovision AWS VPC and IAM resources
        type: xlrelease.ParallelGroup
        tasks:
        - name: Deprovision AWS IAM resources
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/scott-micro-final/aws-cloudformation-scott-micro-final/scott-micro-final-cloudformation-eks-user
        - name: Deprovision AWS VPC
          type: xldeploy.Undeploy
          server: XL Deploy
          deployedApplication: Environments/scott-micro-final/aws-cloudformation-scott-micro-final/scott-micro-final-cloudformation-eks-vpc